<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaAutomoveis [
    <!ELEMENT listaAutomoveis (automovel+)>
    <!ELEMENT automovel (descricao, preco, caracteristicas)>
    <!ATTLIST automovel xml:id ID #REQUIRED>
    <!ELEMENT descricao (#PCDATA)>
    <!ATTLIST descricao combustivel (GASOLINA | GASOLEO | GPL) #REQUIRED>
    <!ELEMENT preco (#PCDATA)>
    <!ELEMENT caracteristicas (cor, quilometragem, fotografia+, obs)>
    <!ELEMENT cor (#PCDATA)>
    <!ATTLIST cor nome CDATA #REQUIRED>
    <!ELEMENT quilometragem (#PCDATA)>
    <!ELEMENT fotografia (#PCDATA)>
    <!ATTLIST fotografia xml:id ID #REQUIRED>
    <!ELEMENT obs (#PCDATA)>


]>
<listaAutomoveis>
    <automovel xml:id="a1">
        <descricao combustivel="GASOLINA">Uma descrição qualquer </descricao>
        <preco></preco>

        <caracteristicas>
            <cor nome="vermelho"/>
            <quilometragem>300</quilometragem>
            <fotografia xml:id="f1"/>
            <fotografia xml:id="f2"/>
            <obs>Isso é uma observação</obs>
        </caracteristicas>
    </automovel>

  
    <automovel xml:id="a2">
        <descricao combustivel="GPL">Outra descrição qualquer</descricao>
        <preco></preco>

        <caracteristicas>
            <cor nome="azul"/>
            <quilometragem></quilometragem>
            <fotografia xml:id="f3"/>
            <fotografia xml:id="f4"/>
            <obs>Isso é uma observação</obs>
        </caracteristicas>
    </automovel>
</listaAutomoveis>
